/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportes;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.ImageObserver;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;


/**
 *
 * @author usuario
 */
public class frmPrinicipal extends javax.swing.JFrame {
    public Image imagenFondo;
    public URL fondo;
    
    /**
     * Creates new form frmPrinicipal
     */
    public frmPrinicipal() {
        initComponents();
        ImageIcon img = new ImageIcon("C:\\Users\\\\Cpu\\Documents\\NetBeansProjects\\Sicar\\logo.png");
//define el icon a tu JFrame
        this.setIconImage(img.getImage());
          
        
        ImageIcon imageVentas= new ImageIcon("src/Imagenes/ventas.png");
        Icon iconoVentas = new ImageIcon(imageVentas.getImage().getScaledInstance(btnventasfecha.getWidth(),btnventasfecha.getHeight() , Image.SCALE_DEFAULT));
        btnventasfecha.setIcon(iconoVentas);
        btnventasfecha.setOpaque(false);
        btnventasfecha.setBackground(new Color(0,0,0,0));
        this.repaint();
        
        //imagen boton btnreportedepartamento
        ImageIcon imageDepartamento= new ImageIcon("src/Imagenes/departamento.png");
        Icon iconoDepartamento = new ImageIcon(imageDepartamento.getImage().getScaledInstance(btnreportedepartamento.getWidth(),btnreportedepartamento.getHeight() , Image.SCALE_DEFAULT));
        btnreportedepartamento.setIcon(iconoDepartamento);
        btnreportedepartamento.setOpaque(false);
        btnreportedepartamento.setBackground(new Color(0,0,0,0));
        this.repaint();
        
        
        //imagen boton btnreporteporcentaje
        ImageIcon imagePorcentaje= new ImageIcon("src/Imagenes/porcentaje.png");
        Icon iconoPorcentaje = new ImageIcon(imagePorcentaje.getImage().getScaledInstance(btnreporteporcentaje.getWidth(),btnreporteporcentaje.getHeight() , Image.SCALE_DEFAULT));
        btnreporteporcentaje.setIcon(iconoPorcentaje);
        btnreporteporcentaje.setOpaque(false);
        btnreporteporcentaje.setBackground(new Color(0,0,0,0));
        this.repaint();
        
        
        
        
    }
    
    public JPanel panel = new JPanel(){
    public void paintComponet(Graphics g){
        g.drawImage(imagenFondo, 0, 0, getWidth(),getHeight(), (ImageObserver) this);
    }
    };
    public void mostrar(JFrame reporte){
        reporte.setLocationRelativeTo(null);
        reporte.setVisible(true);
        reporte.setResizable(false);
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/fondo.png"));
        Image image2 = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image2,0,0,getWidth(),getHeight(),this);
            }
        };
        btnreporteporcentaje = new javax.swing.JButton();
        btnventasfecha = new javax.swing.JButton();
        btnreportedepartamento = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reportes ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 191));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        btnreporteporcentaje.setToolTipText("Reporte de Productos que Conforman el 80% de ventas");
        btnreporteporcentaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreporteporcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteporcentajeActionPerformed(evt);
            }
        });

        btnventasfecha.setToolTipText("Reporte de Salidas");
        btnventasfecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnventasfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventasfechaActionPerformed(evt);
            }
        });

        btnreportedepartamento.setToolTipText("Reporte De ventas Por Departamento");
        btnreportedepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnreportedepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportedepartamentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Reporte departamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(btnventasfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnreportedepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(123, 123, 123)
                        .addComponent(btnreporteporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnventasfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnreportedepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreporteporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreporteporcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteporcentajeActionPerformed
        // TODO add your handling code here:
        frmproductosporcentaje reporte = new frmproductosporcentaje();
        mostrar(reporte);
    }//GEN-LAST:event_btnreporteporcentajeActionPerformed

    private void btnreportedepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportedepartamentoActionPerformed
        // TODO add your handling code here:
        frmReporteDepartamento reporte = new frmReporteDepartamento();
         mostrar(reporte);
    }//GEN-LAST:event_btnreportedepartamentoActionPerformed

    private void btnventasfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventasfechaActionPerformed
        // TODO add your handling code here:
        ReporteVentasFecha reporte = new ReporteVentasFecha();
        mostrar(reporte);
    }//GEN-LAST:event_btnventasfechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrinicipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrinicipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreportedepartamento;
    private javax.swing.JButton btnreporteporcentaje;
    private javax.swing.JButton btnventasfecha;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
