/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportes;

import Metodos.MetodosReporteDepartamento;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class frmReporteDepartamento extends javax.swing.JFrame {

    /**
     * Creates new form frmReporteDepartamento
     */
    Metodos.MetodosReporteDepartamento met = new MetodosReporteDepartamento();
    SimpleDateFormat formatomysql = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat prueba = new SimpleDateFormat("dd/MM/yyyy");
    String fecha1, fecha2;

    public frmReporteDepartamento() {
        initComponents();
        jdcfinal.setDate(new Date());
        jdcinicio.setDate(new Date());
        ImageIcon img = new ImageIcon("C:\\Users\\\\Cpu\\Documents\\NetBeansProjects\\Sicar\\logo.png");
//define el icon a tu JFrame
        this.setIconImage(img.getImage());
    }

//    public void prueba() {
//        try {
//            Calendar inicio = new GregorianCalendar();
//            Calendar fin = new GregorianCalendar();
//            inicio.setTime(new SimpleDateFormat("dd/MM/yyyy").parse(prueba.format(jdcinicio.getDate())));
//            fin.setTime(new SimpleDateFormat("dd/MM/yyyy").parse(prueba.format(jdcfinal.getDate())));
//            int difA = fin.get(Calendar.YEAR) - inicio.get(Calendar.YEAR);
//            int difM = difA * 12 + fin.get(Calendar.MONTH) - inicio.get(Calendar.MONTH);
//
//            System.out.println(difM);
//
//        } catch (ParseException ex) {
//            JOptionPane.showMessageDialog(null, ex);
//        }
//    }
    private void ultimodiames() {
        String date = prueba.format(jdcfinal.getDate());
        LocalDate convertedDate = LocalDate.parse(date, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        convertedDate = convertedDate.withDayOfMonth(
                convertedDate.getMonth().length(convertedDate.isLeapYear()));
        String cadena = convertedDate + "";
        String cadena2 = formatomysql.format(jdcfinal.getDate());
        if (cadena2.equals(cadena)) {
            fecha1 = formatomysql.format(jdcinicio.getDate()) + " 06:00:00";
            fecha2 = formatomysql.format(jdcfinal.getDate()) + " 21:00:00";

        } else {
            cadena = cadena.substring(8, 10);
            JOptionPane.showMessageDialog(null, cadena);
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(jdcfinal.getDate()); // Configuramos la fecha que se recibe
            calendar.add(Calendar.MONTH, -1);
            String fechaultimodia = formatomysql.format(calendar.getTime());
            fechaultimodia = fechaultimodia.substring(0, 8) + calendar.getActualMaximum(calendar.DAY_OF_MONTH) + " 21:00:00";

            calendar.setTime(jdcfinal.getDate());
            calendar.add(Calendar.MONTH, 0);
            String fechaprimerdia = formatomysql.format(calendar.getTime());
            fechaprimerdia = fechaprimerdia.substring(0, 8) + calendar.getActualMinimum(calendar.DAY_OF_MONTH) + " 06:00:00";

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdcinicio = new com.toedter.calendar.JDateChooser();
        jdcfinal = new com.toedter.calendar.JDateChooser();
        btncrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte Por Departamentos");

        jdcinicio.setDateFormatString("dd/MM/yyyy");

        jdcfinal.setDateFormatString("dd/MM/yyyy");

        btncrear.setText("Crear");
        btncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jdcinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdcfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(btncrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdcinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdcfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(btncrear)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearActionPerformed
        // TODO add your andling code here:

        //ultimodiames();
        if (jdcinicio.getDate().after(jdcfinal.getDate())) {
            JOptionPane.showMessageDialog(null, "Error en las Fechas","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            fecha1 = formatomysql.format(jdcinicio.getDate()) + " 06:00:00";
            fecha2 = formatomysql.format(jdcfinal.getDate()) + " 21:00:00";
            //met.GeneraExcel(fecha1, fecha2);
            met.modificaexcel(fecha1, fecha2);
        }

        //

    }//GEN-LAST:event_btncrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrear;
    private javax.swing.JPanel jPanel1;
    public static com.toedter.calendar.JDateChooser jdcfinal;
    public static com.toedter.calendar.JDateChooser jdcinicio;
    // End of variables declaration//GEN-END:variables
}
